config/routes.rb
Rails.application.routes.draw do
  root'flights#index', as: 'flights'
  get 'flights/index'
  resources :bookings, only: [:new, :create, :index, :show]
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, :foreign_key => "departure_airport_id", class_name: "Flight"
  has_many :arriving_flights, :foreign_key => "arrival_airport_id", class_name: "Flight"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, :class_name => "Airport"
  belongs_to :arrival_airport, :class_name => "Airport"
  has_many :bookings
  has_many :passengers, through: :bookings

  def date_formatted
    departure_time.strftime("%m/%d/%Y")
  end

  def self.departure_time_options
    return Flight.select(:departure_time).group('DATE(departure_time)')
                                    .map{ |f| [ f.date_formatted, f.departure_time.to_date ]}
  end

  def self.queried_flights departure_params
    queried_flights = []
    if !departure_params[:departure_airport_id].nil?
      queried_flights = Flight.all
      queried_flights = queried_flights.where(departure_airport_id: departure_params[:departure_airport_id])
      queried_flights = queried_flights.where(arrival_airport_id: departure_params[:arrival_airport_id])
      queried_flights = queried_flights.where("DATE(departure_time) = ?", departure_params[:departure_time].to_date)
    end
    return queried_flights
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  before_save { email.downcase! }

  belongs_to :booking
  has_many :flights, through: :bookings

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @flight = Flight.find(params[:flight_id])
    @num_passengers = params[:num_passengers].to_i
    if @num_passengers < 1 || @num_passengers > 4
      @num_passengers = 1
    end
    @num_passengers.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      flash[:success] = "Booking created!"
      redirect_to @booking
    else
      @flight = Flight.find(booking_params[:flight_id])
      @num_passengers = params[:num_passengers]
      render 'new'
    end
  end

  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private
    def booking_params
      params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :name, :email, :booking_id])
    end
end

app/controllers/flights_controller.rb
include ActionView::Helpers::TextHelper
class FlightsController < ApplicationController
  def index
    # @flight = Flight.new
    @num_passengers = params[:num_passengers] unless params[:num_passengers].nil?
    @queried_flights = Flight.queried_flights(params)
  end

  private
    def flight_params
      params.require(:flight).permit(:departure_airport_id, :arrival_airport_id, :departure_time, :num_passengers)
    end

end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
  def airports_options
    return Airport.all.map{|a| [ "#{a.code}, #{a.name}", a.id ]}
  end

  def num_passenger_options
    return [1,2,3,4].map{|num| [ pluralize(num, 'person'), num ]}
  end

  def departure_time_options
    return Flight.departure_time_options
  end
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/bookings/index.html.erb
<h1>Bookings</h1>

Upcoming Reservations:
<ul>
  <% @bookings.each do |booking| %>
    <li>
      <%= link_to "Booking ##{booking.id}", booking %> |
      Flying out of: <%= booking.flight.departure_airport.name %> |
      Flying to: <%= booking.flight.arrival_airport.name %> |
      Departure time: <%= booking.flight.departure_time %> |
      Flight duration: <%= booking.flight.duration %>
      Passengers: <% booking.passengers.each do |p| %>
        <%= p.name %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to "Find another flight", flights_path %>

app/views/bookings/new.html.erb
<h1>Booking Information</h1>

<div>
  <%= form_for(@booking) do |f| %>
  <%= f.hidden_field :flight_id, value: params[:flight_id] %>

    Departing from: <%= @flight.departure_airport.name %> |
    Arriving to: <%= @flight.arrival_airport.name %> |
    Date: <%= @flight.departure_time %> |
    <%= pluralize(@num_passengers, "passenger") %>

    <ul>
      <%= f.fields_for :passengers do |passenger_form| %>
        <li>
          <%= passenger_form.label :name %>
          <%= passenger_form.text_field :name, required: true %>
          <%= passenger_form.label :email %>
          <%= passenger_form.email_field :email, required: true %>
        </li>
      <% end %>
    </ul>

    <div>
      <%= submit_tag "Create Booking" %>
    </div>
  <% end %>
</div>

<%= link_to "Back to search", flights_path %>

app/views/bookings/show.html.erb
<h1>Booking information</h1>

<ol>
  <li>Flying out of: <%= @booking.flight.departure_airport.name %></li>
  <li>Flying to: <%= @booking.flight.arrival_airport.name %></li>
  <li>Departure time: <%= @booking.flight.departure_time %></li>
  <li>Flight duration: <%= @booking.flight.duration %></li>
  <li>
    Passengers:
    <ul>
      <% @booking.passengers.each do |p| %>
      <li> <%= p.name %> </li>
      <% end %>
      </ul>
  </li>
</ol>
<%= link_to "See all bookings", bookings_path %>

app/views/flights/index.html.erb
<h1>Search for a flight:</h1>

<%= form_tag(flights_path, method: :get) do %>
  <div class = "form row">
    <%= label_tag "Departs from:" %>
    <%= select_tag(:departure_airport_id, options_for_select(airports_options, params[:departure_airport_id])) %>
  </div>
  <div class = "form row">
    <%= label_tag "Arrives at:" %>
    <%= select_tag(:arrival_airport_id, options_for_select(airports_options, params[:arrival_airport_id])) %>
  </div>
  <div class = "form row">
    <%= label_tag "Departure date:" %>
    <%= select_tag(:departure_time, options_for_select(departure_time_options, params[:departure_time])) %>
  </div>
  <div class = "form row">
    <%= label_tag "Number of passengers:" %>
    <%= select_tag(:num_passengers, options_for_select(num_passenger_options, params[:num_passengers])) %>
  </div>

  <div class = "form">
    <%= submit_tag "Search for flights" %>
  </div>
<% end %>

<% unless @queried_flights.empty? %>
  <h3>Select from:</h3>

  <%= form_tag new_booking_path, method: :get do %>

    <%= hidden_field_tag :num_passengers, params[:num_passengers] %>

    <% @queried_flights.each do |flight| %>
      <div class = "form row">
        <%= radio_button_tag(:flight_id, "#{flight.id}", :required => true) %>
        <%= label_tag("flight_id_#{flight.id}", "#{flight.departure_airport.name}") %> |
        <%= label_tag("flight_id_#{flight.id}", "#{flight.arrival_airport.name}") %> |
        <%= label_tag("flight_id_#{flight.id}", "Departure date: #{flight.date_formatted}") %> |
        <%= label_tag("flight_id_#{flight.id}", "Duration: #{pluralize(flight.duration, 'hour')}") %>
      </div>
    <% end %>
    <div class = "form">
      <%= submit_tag "Book flight" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FLIGHTBooker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>